FROM docker.dbc.dk/payara5-micro:latest
LABEL \
    OPEN_AGENCY_URL="Webaddress of open-agency service (required)" \
    ENABLED_PROFILES="list of enabled profiles (required)"
ADD app.json *.war deployments/